### ISSUE TITLE
Please add support installation via composer

### ISSUE THREAD

**Issue by fproject** [sourcetoad/bbii2#1]
It's very helpful if BBii2 can be installed via Composer instead of hard-copying the source file into 'modules' folder.

**Comment by davidjeddy** [comment]
This is top on our list actually, branch 2.0.0-dev is the current iteration of this feature (not done yet but soon(tm)).

**Comment by nguyenbs** [comment]
I'm a fan of Yii and I like your BBii very much. I have used BBii1 in several projects.

Now I wish I could use it in Yii 2.0.

I tried this repo but it has some bugs. How a bout the status now?

Thanks in advance

**Comment by davidjeddy** [comment]
Sadly we are currently backed up with clients so getting back to this will take a bit of time. Sorry for the delay.

**Comment by davidjeddy** [comment]
Composer support added via https://github.com/sourcetoad/bbii2/releases/tag/2.0.0 release.

**Comment by fproject** [comment]
Hi @davidjeddy,
I see in packagist two public packages:

sourcetoad/yii2-bbii2 at https://packagist.org/packages/sourcetoad/yii2-bbii2
sourcetoad/bbii2 at https://packagist.org/packages/sourcetoad/bbii2

Which one is correct?

**Comment by davidjeddy** [comment]
We recommend https://packagist.org/packages/sourcetoad/bbii2
