### ISSUE TITLE
Class 'yii\imperavi\Widget' not found

### ISSUE THREAD

**Issue by fproject** [sourcetoad/bbii2#2]
Could u pls add the list of dependencies of the BBii2?
Thank you!

**Comment by fproject** [comment]
I just added the dependency to "asofter/yii2-imperavi-redactor" but it cannot publish the assets:

```
The file or directory to be published does not exist: /test/vendor/yiisoft/yii2/imperavi/assets
```

**Comment by davidjeddy** [comment]
BBii2 is not yet fully composer compatible, that functionality is on the list for the next iteration.

**Comment by davidjeddy** [comment]
Please provide more information. Bbii2 v2 is now composer compatable.
