### ISSUE TITLE
Fix composer.json schema

### ISSUE THREAD

**Issue by h3d-thanhpv** [sourcetoad/bbii2#5]
"./composer.json" does not match the expected JSON schema:
authors[0] : The property - website - is not defined and the definition does not allow additional properties

**Comment by h3d-thanhpv** [comment]
Pls add require package to composer.json
Thank you!

**Comment by davidjeddy** [comment]
Bbii2 AFAIK does not have any dependencies. Maybe CKEdit if you turn it on but atm it is not.

**Comment by h3d-thanhpv** [comment]
I found in your code has yiisoft/yii2-jui, so it should be in composer.json file

**Comment by davidjeddy** [comment]
Added, TY.
