### ISSUE TITLE
Undefined index 'user' - Should check array_key_exists

### ISSUE THREAD

**Issue by h3d-thanhpv** [sourcetoad/bbii2#7]
After I install forum module via composer by guide in readme, run migrations, it has a bug on file `BBiiController` line 115.
I found that `Yii::$app->authManager->getRolesByUser(\Yii::$app->user->identity->id )` is array, but it don't have index `user`. You should check `array_key_exists` this array.
And I think you should add more information in install guide. like rbac migration and init data in your migrations.

**Comment by davidjeddy** [comment]
Please submit PR with correction.

Submit ticket requesting filler migration data.

**Comment by h3d-thanhpv** [comment]
My solution:

```
// rbac role "moderator"
        if (\Yii::$app->authManager) {
            /** @var array $role */
            $role = Yii::$app->authManager->getRolesByUser(\Yii::$app->user->identity->getId());
            if(!is_null($role) && is_array($role) && array_key_exists('moderator', $role)) {
                return true;
            }
        }
```

I don't know your rbac data, so I create my init rbac.
Run this migrations:
`yii migrate --migrationPath=@yii/rbac/migrations`
This is file to run in console.

```
namespace app\commands;

use Yii;
use yii\console\Controller;

class RbacController extends Controller
{
    public function actionInit()
    {
        $auth = Yii::$app->authManager;

        $moderator = $auth->createRole('moderator');
        $auth->add($moderator);

        $admin = $auth->createRole('admin');
        $auth->add($admin);
        $auth->addChild($admin, $moderator);

        $auth->assign($admin, 1);
    }
}
```

I think it should place in migration data or install guide

**Comment by davidjeddy** [comment]
Please submit PR with correction.
https://help.github.com/articles/using-pull-requests/
